# Generated by Django 3.0.5 on 2020-05-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=100)),
                ('currency_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_currency',
            },
        ),
    ]
