# Generated by Django 3.0.5 on 2020-05-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='content_images')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('content_type', models.IntegerField(choices=[(0, 'Free'), (1, 'Paid')], default=0)),
            ],
            options={
                'db_table': 'tbl_post',
                'ordering': ['-created_on'],
            },
        ),
    ]
