# Generated by Django 3.0.5 on 2020-05-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        ('content', '0002_auto_20200503_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='league.Leaguetype'),
        ),
    ]
