# Generated by Django 3.0.5 on 2020-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200509_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='merchantId',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
