# Generated by Django 3.0.5 on 2020-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200514_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
