# Generated by Django 3.0.7 on 2020-07-17 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('M_PESA', '0002_auto_20200515_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
