# Generated by Django 3.0.5 on 2020-05-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leaguetype',
            table='tbl_legue_type',
        ),
    ]
